# Generated by Django 5.0.2 on 2024-03-11 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sigas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='pessoa',
        ),
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='numero_matricula',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='idade',
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso_superior',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='matricula',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_completo',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Adm',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
