# Generated by Django 5.0.4 on 2024-07-31 02:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sigas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('duracao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={},
        ),
        migrations.AlterModelManagers(
            name='pessoa',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='numero_matricula',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='username',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='salario',
        ),
        migrations.AddField(
            model_name='aluno',
            name='data_de_ingresso',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='aluno',
            name='situacao_academica',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_completo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professor',
            name='data_admissao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='professor',
            name='remuneracao',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='professor',
            name='turno',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ManyToManyField(related_name='aluno', to='app_sigas.curso'),
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('turno', models.CharField(blank=True, max_length=100, null=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_sigas.curso')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(related_name='alunos', to='app_sigas.disciplina'),
        ),
        migrations.CreateModel(
            name='InscricaoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sigas.disciplina')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sigas.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(default='')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='app_sigas.aluno')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='app_sigas.registroatividade')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('descricao', models.TextField()),
                ('data', models.DateField(default=datetime.date.today)),
                ('disciplina', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_sigas.disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='registroatividade',
            name='registro_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='app_sigas.registroaula'),
        ),
        migrations.CreateModel(
            name='RegistroFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_faltas', models.IntegerField(default=0)),
                ('data', models.DateField(default=datetime.date.today)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sigas.aluno')),
                ('aula', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_sigas.registroaula')),
            ],
        ),
        migrations.DeleteModel(
            name='Adm',
        ),
    ]
