# Generated by Django 4.2.9 on 2024-03-12 13:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sigas', '0002_remove_professor_pessoa_alter_aluno_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_admissao', models.DateField(default=datetime.date.today)),
                ('turno', models.CharField(default='', max_length=100)),
                ('remuneracao', models.FloatField()),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_sigas.pessoa')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('professor', models.ManyToManyField(related_name='disciplinas', to='app_sigas.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('duracao', models.CharField(max_length=100)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='app_sigas.aluno')),
                ('disciplinas', models.ManyToManyField(related_name='cursos', to='app_sigas.disciplina')),
            ],
        ),
    ]
