# Generated by Django 4.2.9 on 2024-03-12 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_sigas', '0003_professor_disciplina_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={},
        ),
        migrations.AlterModelManagers(
            name='pessoa',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='username',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
