# Generated by Django 4.2.9 on 2024-03-13 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sigas', '0005_remove_aluno_curso_superior_remove_curso_aluno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sigas.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroFalta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sigas.aluno')),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_falta', to='app_sigas.diario')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('descricao', models.TextField()),
                ('diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_aula', to='app_sigas.diario')),
            ],
        ),
    ]
