# Generated by Django 4.2.9 on 2024-03-13 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sigas', '0006_diario_registrofalta_registroaula'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofalta',
            name='aula',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_sigas.registroaula'),
        ),
        migrations.AddField(
            model_name='registrofalta',
            name='quantidade_faltas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registrofalta',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
