# Generated by Django 4.2.9 on 2024-03-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sigas', '0007_registrofalta_aula_registrofalta_quantidade_faltas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroaula',
            name='diario',
        ),
        migrations.RemoveField(
            model_name='registrofalta',
            name='diario',
        ),
        migrations.DeleteModel(
            name='Diario',
        ),
    ]
