# Generated by Django 4.2.9 on 2024-03-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sigas', '0008_remove_registroaula_diario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroaula',
            name='disciplina',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app_sigas.disciplina'),
        ),
    ]
