# Generated by Django 5.0.2 on 2024-03-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sigas', '0009_registroaula_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='curso',
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ManyToManyField(default='', related_name='aluno', to='app_sigas.curso'),
        ),
    ]
