# Generated by Django 5.0.2 on 2024-03-19 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sigas', '0011_remove_professor_disciplina_remove_disciplina_curso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('registro_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='app_sigas.registroaula')),
            ],
        ),
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(default='')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sigas.aluno')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sigas.registroatividade')),
            ],
        ),
    ]
