# Generated by Django 5.0.2 on 2024-03-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sigas', '0012_registroatividade_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(related_name='alunos', to='app_sigas.disciplina'),
        ),
    ]
